###
POST http://localhost:8081/v1/api/createNewUser
Content-Type:  application/json
# x-api-key : f8db3f5f7e925f335b592f30a4b224811d30f5a623d1a430e11cb3d166215da3

{
    "name" : "tnnn",
    "password" :"1233219",
    "email" :"8t12379@gmail.com",
    "phone" : "1969976767684",
    "role" : "tenant"
}

###
POST http://localhost:8081/v1/api/refresh-tokken
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRfaWQiOjIsImlhdCI6MTcxODc2OTg3MSwiZXhwIjoxNzUwMzI3NDcxfQ.Ic0tI2jBZz_I4E38j95eL9J62TsdH0frROxN0Xy3R-0"
}

###
GET http://localhost:8081/v1/api/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRfaWQiOjIsImlhdCI6MTcxODc3MTI5MCwiZXhwIjoxNzE4NzcxMzUwfQ.fm69z8k0obZc4QxBPeEfCuDUymKwND4Mc-goKYl8Xus

###
POST http://localhost:8081/v1/api/logout
Content-Type: application/json

{
    
    "athorization" : "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjU4LCJlbWFpbCI6Ijh0MTIzNzlAZ21haWwuY29tIiwiaWF0IjoxNzIxNjExMDIzLCJleHAiOjE3MjE3ODM4MjN9.P8C1DcrElXE0esovmJqer22Oful7R8PbCQkh9cw4kuLFA640ECmfxROBq86TNy1TI0UoVLvBZYSNHdy6RANY4gXBxvyBciGWSZgSStZzUtOxsv88r-XBwBVRKhel3gAnna0tlwpDGEWJ_6Hmm4xWcXh11BzRuVuO8gXVFzW1Byn44iGnijrw_ex0_xsk8ZJ5EzN9joJpqjzu0OlUr6Dy-oBh8v_EWuy5BCCxkw4hS2IL9DOLi9i-a_4FpE6F4CGOl4TKisCBbOZWc9sU1lnbsq8SX0qzxl7lXY_jBAl13d41jxSIbc-MKUjMafQ_SfOXSK4H6Lmu_C890hw0OpGwdA"
}

###
POST http://localhost:8081/v1/api/login
Content-Type: application/json


{
    "email" :"8t12379@gmail.com",
   "password" :"1233219",
    "refreshToken" :"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjU4LCJlbWFpbCI6Ijh0MTIzNzlAZ21haWwuY29tIiwiaWF0IjoxNzIxNzk2MTU3LCJleHAiOjE3MjI0MDA5NTd9.Rt3xNSMen_U8OdTgz8cDwl-Fd__KRaiXO4igAoOnR9LGZ2t7vw-gHo24_NGqT7Ek4Bc71QllJZms1HWgE01AYZMUgfEtcMB12fi21g3XCjMklJanRBSmvpWTMOldHnj5droVvhSURVBPPXxUFBzO67j1S8Z3AGnLoqB60xUqtkqEejs3Lwc8q--e8cBIdRhBEooPTGDbIgMQ9VRtafOqIO8bQjjlyVbW0fCVWYHRdk6iPBboxkFMUIugkFhpLQf0uV_LuDLumIvhxkUiY_iqQjCntZFnx-gdDnP938neM147RnAHa0KizfG9Zef9CC_bMt5GTXL0GjQx8Wo79VxQWQ"
}


###
