###
POST http://localhost:8081/v1/api/createNewUser
Content-Type:  application/json
# x-api-key : f8db3f5f7e925f335b592f30a4b224811d30f5a623d1a430e11cb3d166215da3

{
    "name" : "tnnn",
    "password" :"1233219",
    "email" :"8881214637@gmail.com",
    "phone" : "841155441884",
    "role" : "tenant"
}

###
POST http://localhost:8081/v1/api/refresh-tokken
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRfaWQiOjIsImlhdCI6MTcxODc2OTg3MSwiZXhwIjoxNzUwMzI3NDcxfQ.Ic0tI2jBZz_I4E38j95eL9J62TsdH0frROxN0Xy3R-0"
}

###
GET http://localhost:8081/v1/api/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRfaWQiOjIsImlhdCI6MTcxODc3MTI5MCwiZXhwIjoxNzE4NzcxMzUwfQ.fm69z8k0obZc4QxBPeEfCuDUymKwND4Mc-goKYl8Xus

###
POST http://localhost:8081/v1/api/logout
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRfaWQiOjIsImlhdCI6MTcxODc4OTg2NCwiZXhwIjoxNzUwMzQ3NDY0fQ.mONAuKuHTfw5g4ymWDaUjQIa5UqbJ3HRtR9AOIfWf3U"
}


###
