###
POST http://localhost:8081/v1/api/access/signUp
Content-Type:  application/json
# x-api-key : f8db3f5f7e925f335b592f30a4b224811d30f5a623d1a430e11cb3d166215da3

{
    "name" : "tnnn",
    "password" :"1233219",
    "email" :"123t12345@gmail.com",
    "phone" : "1936448664",
    "role" : "tenant"
}

###
POST http://localhost:8081/v1/api/refresh-tokken
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRfaWQiOjIsImlhdCI6MTcxODc2OTg3MSwiZXhwIjoxNzUwMzI3NDcxfQ.Ic0tI2jBZz_I4E38j95eL9J62TsdH0frROxN0Xy3R-0"
}

###
GET http://localhost:8081/v1/api/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRfaWQiOjIsImlhdCI6MTcxODc3MTI5MCwiZXhwIjoxNzE4NzcxMzUwfQ.fm69z8k0obZc4QxBPeEfCuDUymKwND4Mc-goKYl8Xus

###
POST http://localhost:8081/v1/api/access/logout
Content-Type: application/json

{
    "athorization" : "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhODUwMjVjMS1iMzkzLTRmM2YtOGE0Yy0yMzNjMzRkNTQxZTAiLCJlbWFpbCI6IjEyM3QxMjM0NUBnbWFpbC5jb20iLCJpYXQiOjE3MjMyMzczNTIsImV4cCI6MTcyMzg0MjE1Mn0.wlklIcSsSaIKu2tJzUBR46xkM-04R7blY4j9I2q9mwE4CqgYa206J9Yh58n8BWj46UNd3SfAHZvxw0b8bovw6IosNpw-FIR_sI9wJM7naBi_CSWtLqnRgTvCqSCIQ28CrBKrPgv5CtQWFsL4_iuFwn5ledr3mu6QPavEjh8-3QtB-x7Z8QsGp5AAFjrSZxcVV0D_6yQ5uUNFjjZI-F4rKzc1dwNciMBwPx6zhyPIEdHdxOkcue2p1FCI4LWSG5aKrlECFx0z7e_sKqoj2B7G2jtzm0yohC21yJwj6G1cmrE4eOnX2lE-TZ9sjNl879_aPwQ8OPG2bnwrIQZB5Z45zw"
}

###
POST http://localhost:8081/v1/api/access/login
Content-Type: application/json


{
    "email" :"123t123459@gmail.com",
    "password" :"1233219",
     "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwYTg2YjZlMS1kNDFjLTQyMTEtOGQ5ZC1iOGM5MmMxNjk2MWYiLCJlbWFpbCI6IjEyM3QxMjM0NTlAZ21haWwuY29tIiwiaWF0IjoxNzIzMjYzMDIxLCJleHAiOjE3MjM4Njc4MjF9.EoZVgS4Y61xPrc-QE75t46uCw2PBLcIEYEMtQOE8HKP1gJIuRzWbORN36L9NoLwNs-huQA80yEx08vW7BXk_6W9aPrBu-OLJnYYSfMMzMfflQ_JpOjfBKhzC4qfOe1-lyDrngp6PkhN1mhSJ1v0aZxslN0P_bBmuggln5GDSYRxx1XRvXGdrv_t00qQPQ95cMg8jrea3fT6ECEPxkdkVRe2DuDqRgunqkS_pBk-0eglIuQBPdrTOjbRlEw5NrXGkH3aNI9CprzBrusQFsKtNd8AwqWD9CyxCjzayj2AjjEzapSE-qwEj7gRRXr_05ADgMGvUrylzCRq8FFLuqDENxQ"
}


###
